import * as THREE from 'three';
import { QUALITY, TIME_OF_DAY } from '../config/ArtDirection.js';

/**
 * Lighting — sun, sky ambient, and the image-based environment.
 *
 * The env map is generated by rendering the Sky dome into a cube target, so
 * ambient/specular response always matches the visible sky. This is the cheapest
 * way to get the "everything sits in the same light" coherence AAA renderers have.
 */
export class Lighting {
  constructor(engine, sky) {
    this.engine = engine;
    this.sky = sky;
    this.order = -50;

    this.sun = new THREE.DirectionalLight(0xffffff, 6.6);
    this.sun.castShadow = true;
    this.sun.shadow.mapSize.set(QUALITY.shadowMapSize, QUALITY.shadowMapSize);
    this.sun.shadow.camera.near = 1;
    this.sun.shadow.camera.far = 900;
    this.sun.shadow.bias = -0.00035;
    this.sun.shadow.normalBias = 0.06;
    this.sun.shadow.radius = 2.2;
    const d = 120;
    Object.assign(this.sun.shadow.camera, { left: -d, right: d, top: d, bottom: -d });
    this.sun.shadow.camera.updateProjectionMatrix();
    this.sunTarget = new THREE.Object3D();
    engine.scene.add(this.sun, this.sunTarget);
    this.sun.target = this.sunTarget;

    this.hemi = new THREE.HemisphereLight(0x9fb6d8, 0x6b5c46, 1.0);
    engine.scene.add(this.hemi);

    // Bounce light: sand kicks a lot of warm light back up into undersides.
    this.bounce = new THREE.DirectionalLight(0xc9a878, 0.55);
    this.bounce.position.set(0, -1, 0);
    engine.scene.add(this.bounce);

    this.sunDirection = new THREE.Vector3(0.4, 0.5, -0.75).normalize();
    this.preset = { ...TIME_OF_DAY.afternoon };

    this.pmrem = new THREE.PMREMGenerator(engine.renderer);
    this.pmrem.compileEquirectangularShader();
    this._envScene = new THREE.Scene();
    this._envDirty = true;
    this._envTarget = null;

    this.setTimeOfDay('afternoon');
  }

  setTimeOfDay(nameOrPreset) {
    const p = typeof nameOrPreset === 'string' ? TIME_OF_DAY[nameOrPreset] : nameOrPreset;
    if (!p) return;
    this.preset = { ...p };
    this.engine.timeOfDay = this.preset;

    const el = THREE.MathUtils.degToRad(p.sunElevation);
    const az = THREE.MathUtils.degToRad(p.sunAzimuth);
    this.sunDirection.set(
      Math.cos(el) * Math.sin(az),
      Math.sin(el),
      Math.cos(el) * Math.cos(az),
    ).normalize();

    this.sun.color.setRGB(...p.sunColor, THREE.LinearSRGBColorSpace);
    this.sun.intensity = p.sunIntensity;
    // The PMREM sky env supplies the sky half of the ambient; a HemisphereLight
    // on top of it double-counts and washes the image out. Keep hemi at zero and
    // express ambient strength through environmentIntensity instead.
    this.hemi.color.setRGB(...p.ambientColor, THREE.LinearSRGBColorSpace);
    this.hemi.intensity = 0.0;
    this.hemi.groundColor.setRGB(0.30, 0.255, 0.19, THREE.LinearSRGBColorSpace);
    this.bounce.intensity = 0.40 * p.ambientIntensity;
    this.envIntensity = 0.8 * p.ambientIntensity;
    this.engine.scene.environmentIntensity = this.envIntensity;

    this.sky.apply(p, this.sunDirection);

    const fogColor = new THREE.Color().setRGB(...p.fogColor, THREE.LinearSRGBColorSpace);
    this.engine.scene.fog = new THREE.FogExp2(fogColor, p.fogDensity);

    if (this.engine.pipeline) this.engine.pipeline.exposure = p.exposure;
    this._envDirty = true;
  }

  _rebuildEnv() {
    // Render the sky dome alone into a PMREM cube for IBL.
    const skyMesh = this.sky.mesh;
    const prevParent = skyMesh.parent;
    // The sun is already a DirectionalLight; leaving its disc in the IBL would
    // double-count it as a colossal ambient term.
    const prevDisc = this.sky.material.uniforms.uSunDiscScale.value;
    this.sky.material.uniforms.uSunDiscScale.value = 0.0;
    this._envScene.add(skyMesh);
    skyMesh.position.set(0, 0, 0);
    skyMesh.scale.setScalar(500);
    if (this._envTarget) this._envTarget.dispose();
    this._envTarget = this.pmrem.fromScene(this._envScene, 0.02, 0.1, 1000);
    this.engine.scene.environment = this._envTarget.texture;
    this.engine.scene.environmentIntensity = this.envIntensity ?? 0.8;
    this.sky.material.uniforms.uSunDiscScale.value = prevDisc;
    if (prevParent) prevParent.add(skyMesh);
    this._envDirty = false;
  }

  update(dt, engine) {
    if (this._envDirty) this._rebuildEnv();

    // Keep the shadow frustum centred a little ahead of the camera so the
    // budget is spent on what the player actually sees.
    const cam = engine.camera;
    const fwd = new THREE.Vector3();
    cam.getWorldDirection(fwd);
    const focus = cam.position.clone().addScaledVector(fwd, 55);
    focus.y = 0;
    this.sunTarget.position.copy(focus);
    this.sun.position.copy(focus).addScaledVector(this.sunDirection, 300);
    this.sun.updateMatrixWorld();
  }
}
